version: '3.8'

services:
  backend:
    build:
      context: ./backend_php
      dockerfile: Dockerfile
    volumes:
      - ./backend_php:/var/www
    networks:
      - app-network
    env_file:
      - ./backend_php/.env

  frontend:
    build:
      context: ./frontend
    ports:
      - '80:80'
    networks:
      - app-network
    env_file:
      - ./frontend/.env

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./backend_php:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
